/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/test");
            Statement statement = conn.createStatement();
            ResultSet result = statement.executeQuery("SELECT * FROM users;");
            int id = result.getInt("id");
            String name = result.getString("name");
            String email = result.getString("email");

            System.out.println("id: " + id);
            System.out.println("name: " + name);
            System.out.println("email: " + email);

        } catch (SQLException e) {
            System.out.println("error code: " + e.getErrorCode());
            System.out.println("message: " + e.getMessage());
        }

        System.out.println(new App().getGreeting());
    }
}
